# Generated by Django 3.1.5 on 2021-01-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
