# Generated by Django 3.1.5 on 2021-01-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20210120_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
